import Header from "@/components/content/layout/header/header";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Providers } from "./providers";
import Footer from "@/components/content/layout/footer/page";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sabr market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <div className="">
            <div className="max-w-[1240px] mx-auto">{children}</div>
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
